version: '3'

services:
  ide_mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE    
    command: mysqld --default-authentication-plugin=mysql_native_password      
    container_name: ide_mysql
    hostname: ide_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 4815162342
      MYSQL_DATABASE: ide_db_dev
    ports:
      - "3306:3306"
    volumes:
      - "./ide/build/database/mysql:/var/lib/mysql"
      # - "./ide/build/database/dumps/init_script.sql:/docker-entrypoint-initdb.d/init_script.sql"      
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2000M
  ide_dev:
    image: scaaseu/devops:ide_dev
    build: ./ide/build
    container_name: ide_dev
    hostname: ide_dev
    restart: on-failure
    environment:
      ROOT: 'TRUE'
      PASSWORD: 4815162342    
    ports:
      - "8787:8787"
      - "4815:4815"
    volumes:
      - "./ide/persistent:/home/rstudio/persistent"
    stdin_open: true
    tty: true
    depends_on:
      - ide_mysql    
    deploy:
      resources:
        limits:
          cpus: "8.0"
          memory: 8000M
